#   Copyright 2017 data.world, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

version: 2

resources:
  defaults: &defaults
    docker:
      - image: circleci/openjdk:8u171-jdk-stretch  # 8u181-jdk-stretch crashes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925

    environment:
      _JAVA_OPTIONS: "-Xmx512m -Xms512m"

  setup_env: &setup_env
    run:
      name: Install prism
      command: curl https://raw.githubusercontent.com/stoplightio/prism/master/install.sh | sudo sh

jobs:

  build:
    <<: *defaults
    steps:
    - checkout
    - *setup_env

    - restore_cache:
        key: dependency-cache-{{ checksum "pom.xml" }}

    - run:
        name: Maven build
        command: mvn clean verify -s settings.xml

    - run:
        name: Prism
        command: prism conduct --spec src/main/resources/world/data/api/swagger.json spec/*

    - save_cache:
        key: dependency-cache-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

    - run:
        name: Extract test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;

    - store_test_results:
        path: ~/junit

    - persist_to_workspace:
        root: /home/circleci/
        paths:
        - project

  deploy:
    <<: *defaults
    steps:
      - checkout
      - *setup_env

      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}

      - deploy:
          name: Maven deploy
          command: mvn deploy -s settings.xml

      - deploy:
          name: Maven release
          command: ./mvn-release.sh

workflows:
  version: 2
  build:
    jobs:
      - build
